### ISSUE TITLE
Building target fails on windows

### ISSUE THREAD

**Issue by HendrikMennen** [enjoy-digital/litex#726] opened 2020-12-10 14:34 UTC
Looks like the path is missing slashes?

![image](https://user-images.githubusercontent.com/25281882/101785387-f87c5700-3afc-11eb-996c-7a8be970f529.png)
```
INFO:SoCBusHandler:Interconnect: ←[1mInterconnectShared←[0m (←[1m2←[0m <-> ←[1m4←[0m).
make: Entering directory `C:/Users/HendrikMennen/Documents/VHDPlus/Litex/litex-boards/litex_boards/targets/build/de10lite/software/libcompiler_rt'
 CC       umodsi3.o
riscv64-unknown-elf-gcc.exe: error: C:UsersHendrikMennenDocumentsVHDPlusLitexpythondata-software-compiler_rtpythondata_software_compiler_rtdata/lib/builtins/umodsi3.c: No such file or directory
riscv64-unknown-elf-gcc.exe: fatal error: no input files
compilation terminated.
make: *** [umodsi3.o] Error 1
make: Leaving directory `C:/Users/HendrikMennen/Documents/VHDPlus/Litex/litex-boards/litex_boards/targets/build/de10lite/software/libcompiler_rt'
Traceback (most recent call last):
  File "de10lite.py", line 128, in <module>
    main()
  File "de10lite.py", line 121, in main
    builder.build(run=args.build)
  File "c:\users\hendrikmennen\documents\vhdplus\litex\litex\litex\soc\integration\builder.py", line 210, in build
    self._generate_rom_software(not self.soc.integrated_rom_initialized)
  File "c:\users\hendrikmennen\documents\vhdplus\litex\litex\litex\soc\integration\builder.py", line 190, in _generate_rom_software
    subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', 'C:\\Users\\HendrikMennen\\Documents\\VHDPlus\\Litex\\litex-boards\\litex_boards\\targets\\build\\de10lite\\software\\libcompiler_rt', '-f', 'c:\\users\\hendrikmennen\\documents\\vhdplus\\litex\\litex\\litex\\soc\\software\\libcompiler_rt\\Makefile']' returned non-zero exit status 2.
```

**Comment by xobs** [comment] 2020-12-10 14:35
This could be a duplicate of https://github.com/enjoy-digital/litex/issues/287

Do you have `sh.exe` in your PATH?

**Comment by HendrikMennen** [comment] 2020-12-10 14:37
yes I have `sh.exe` in my PATH

**Comment by xobs** [comment] 2020-12-10 14:41
What if you set SHELL=cmd.exe?

```powershell
$env:SHELL = "cmd.exe"
```

**Comment by HendrikMennen** [comment] 2020-12-10 14:44
Doesn't seem to change anything for me

**Comment by enjoy-digital** [comment] 2020-12-11 13:25
Can you provide the generated files (create an archive of build/de10lite), this will be useful to understand the issue.

**Comment by HendrikMennen** [comment] 2020-12-11 22:19
gateware folder is empty.

software:
![image](https://user-images.githubusercontent.com/25281882/101960123-01f1e600-3c07-11eb-8998-2dc8e901abab.png)

full archive:
[de10lite.zip](https://github.com/enjoy-digital/litex/files/5681839/de10lite.zip)

**Comment by enjoy-digital** [comment] 2020-12-21 09:37
@HendrikMennen: both #726 and #728 are duplicates and I think @leonbeier is your colleague, let's continue the discussion all together in #728.

**Closed by enjoy-digital** 2020-12-21 09:37 UTC
Labels: bug?, question
