### ISSUE TITLE
Booting with Custom root file system on nexys4DDR

### ISSUE THREAD

**Issue by chriswils95** [enjoy-digital/litex#960] opened 2021-06-28 21:43 UTC
I am trying to boot linux from a sd card with a custom root file system on my nexys4ddr board.
Steps taken was:

    create a custom root file system that contains startup scripts(.tar or .cpio file)
    edit the boot.json file to use my root file system instead of the rootfs.cpio file with the same address
    Anytime i boot up it get stuck. I attached the uart output.
![Screenshot from 2021-06-28 13-39-38](https://user-images.githubusercontent.com/65049496/123707824-8fa1c580-d827-11eb-91d3-d207fa51134c.png)

**Comment by enjoy-digital** [comment] 2021-06-29 07:22
Hi @chriswils95,

we'll need more information to be able to help. Please make sure to read https://github.com/enjoy-digital/litex/wiki/Feedback-Contribution-Support to have a better understanding of the minimal information we need to simplify support.

From what I understand, you are adapting a blog/tutorial written for another board to the nexys4ddr, so we to provide help we need:
- The command line that has been used to generate the Nexys4DDR design.
- A link to the blog/tutorial.
- The way you are booting the kernel images, is it also from SDCard?
- The way you built the kernel images.

In addition to this, if you want to share the bitstream + linux images, it can help us reproduce the issue on a local Nexys4DDR.

Thanks.

**Comment by enjoy-digital** [comment] 2021-06-29 07:24
Closing since duplicate of https://github.com/litex-hub/linux-on-litex-vexriscv/issues/237.

**Closed by enjoy-digital** 2021-06-29 07:25 UTC
Labels: bug?, question
