### ISSUE TITLE
Trying to Run Litex inside linux-on-litex-vexriscv

### ISSUE THREAD

**Issue by natanvotre** [enjoy-digital/litex#379] opened 2020-02-09 23:46 UTC
I am getting this error when I am trying to run ./sim.py on [linux-on-litex-vexriscv](https://github.com/litex-hub/linux-on-litex-vexriscv):

```
make: Entering directory '/home/natan/linux-on-litex-vexriscv/build/sim/software/libcompiler_rt'
make: *** No rule to make target 'umodsi3.o', needed by 'libcompiler_rt.a'.  Stop.
make: Leaving directory '/home/natan/linux-on-litex-vexriscv/build/sim/software/libcompiler_rt'
Traceback (most recent call last):
  File "./sim.py", line 224, in <module>
    main()
  File "./sim.py", line 215, in main
    trace_end   = int(args.trace_end))
  File "/home/natan/linux-on-litex-vexriscv/litex/soc/integration/builder.py", line 169, in build
    self._generate_software(not self.soc.integrated_rom_initialized)
  File "/home/natan/linux-on-litex-vexriscv/litex/soc/integration/builder.py", line 152, in _generate_software
    subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '/home/natan/linux-on-litex-vexriscv/build/sim/software/libcompiler_rt', '-f', '/home/natan/linux-on-litex-vexriscv/litex/soc/software/libcompiler_rt/Makefile']' returned non-zero exit status 2
```

I tried to run manually `make -C /home/natan/linux-on-litex-vexriscv/build/sim/software/libcompiler_rt -f /home/natan/linux-on-litex-vexriscv/litex/soc/software/libcompiler_rt/Makefile` and I got this error

```
make: Entering directory '/home/natan/linux-on-litex-vexriscv/build/sim/software/libcompiler_rt'
make: *** No rule to make target 'umodsi3.o', needed by 'libcompiler_rt.a'.  Stop.
make: Leaving directory '/home/natan/linux-on-litex-vexriscv/build/sim/software/libcompiler_rt'
```

I think that riscv-gcc is not compiling properly, but I am a benniger on this platform and I couldn't solve.

Does someone can help me?
I tried to run using Ubuntu 18.04, docker and also a gcloud instace Debian 9

**Comment by enjoy-digital** [comment] 2020-02-10 08:14
This is a duplicate of https://github.com/litex-hub/linux-on-litex-vexriscv/issues/98, i just answered there.

**Closed by enjoy-digital** 2020-02-10 08:14 UTC
