### ISSUE TITLE
Booting a lightweight image of linux on the litex simulator 

### ISSUE THREAD

**Issue by sramichetty20019** [enjoy-digital/litex#2013] opened 2024-07-11 00:08 UTC
Hi everyone, i have run the Litex simulator with Linux image as directed in the repository i am using verilator based simulation, however i want to speedup the boot process and the time it takes to run commands on the bootup image. Is it possible to use any other linux distribution to do this, or else do you guys any tips for me to speed up the process , kindly let me know

**Comment by gsomlo** [comment] 2024-07-11 17:32
duplicate of https://github.com/litex-hub/linux-on-litex-rocket/issues/43

**Closed by gsomlo** 2024-07-11 17:32 UTC
